spring.application.name=soft

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/soft
spring.datasource.username=soft
spring.datasource.password=soft
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect